package world;

import java.util.ArrayList;

public class Zone {

	private String zoneName 	= "This needs to be set";
	private ArrayList<Room> rooms = new ArrayList<Room>();
	
	
	public String getZoneName() {
		return zoneName;
	}
	public void setZoneName(String zoneName) {
		this.zoneName = zoneName;
	}
	public ArrayList<Room> getRooms() {
		return rooms;
	}
	
	public boolean addRoom(Room room){
		rooms.add(room);
		return true;
	}
	
	public void setRooms(ArrayList<Room> rooms) {
		//TODO: this is autogenerated fix this
	}
	
}
