package world;

import java.util.ArrayList;

public class Zone {

	private String zoneName 	= "This needs to be set";
	private String zoneID = ReservedZones.UNINTIATEDZONE;
	private ArrayList<Room> rooms = new ArrayList<Room>();
	private Map map = new Map();
	
	public Zone(){
		map.initMap();
	}
	
	public Map getMap(){
		return this.map;
	}
	
	public boolean setWholeMap(Map map){
		this.map = map;
		return true;
	}
	
	public String getZoneName() {
		return zoneName;
	}
	public void setZoneName(String zoneName) {
		this.zoneName = zoneName;
	}
	public void setZoneID(String str){
		this.zoneID = str;
	}
	public String getZoneID(){
		return this.zoneID;
	}
	
	public ArrayList<Room> getAllRooms() {
		return rooms;
	}
	
	public ArrayList<String> listAllRooms(){
		int i = 0;
		ArrayList<String> roomlist = new ArrayList<String>();
		while(i<rooms.size()){
			Room rm = getRoomByIndex(i);
			roomlist.add("Room #"+i);
			roomlist.add(rm.getRoomName());
			roomlist.add(rm.getRoomDescription()+"\n");
			i++;
		}
		return roomlist;
	}
	
	public ArrayList<String> slistAllRooms(){
		int i = 0;
		ArrayList<String> roomlist = new ArrayList<String>();
		while(i<rooms.size()){
			Room rm = getRoomByIndex(i);
			roomlist.add(i+".");
			roomlist.add(rm.getRoomName()+"\n");
			i++;
		}
		return roomlist;
	}
	
	public int addRoom(Room room){
		Room rm = room;
		int index = 0;
		boolean unique = true;
		do {
			unique = true;
			for (int i = 0; i < rooms.size(); i++){
				if (rooms.get(i).getIndex() == index){
					unique = false;
					index++;
					break;
				}
			}
		} while (!unique);
		rm.setIndex(index);
		rooms.add(rm);
		return index;
	}
	
	public void setRooms(ArrayList<Room> rooms) {
		//TODO: this is autogenerated fix this
	}
	
	public Room getRoomByIndex(int index){
		for (int i = 0; i < rooms.size(); i++){
			if (rooms.get(i).getIndex() == index){
				return rooms.get(i);
			}
		}
		
		return null;
	}
	
	
	
}
